#ifndef STRUCTS_H
#define STRUCTS_H
#include <mavlink/ardupilotmega/mavlink.h>
#include <QMap>
#include <QVariant>


enum VALUE_TYPE
{
    FLOAT_TYPE,
    UINT8_T_TYPE,
    INT8_T_TYPE,
    UINT16_T_TYPE,
    INT16_T_TYPE,
    UINT32_T_TYPE,
    INT32_T_TYPE,
    UINT64_T_TYPE
};

struct ValueToFollow
{
    QVariant valuePointer;
    int valueType;
    QString name;
    ValueToFollow(){};
    ValueToFollow(QVariant valuePointer, int valueType, QString name)
    {
        this->valuePointer = valuePointer;
        this->valueType = valueType;
        this->name = name;
    }
};
Q_DECLARE_METATYPE(ValueToFollow)



enum VALUE_DIALOG_RESULT
{
    VALUE_DIALOG_GOT_RESULT,
    VALUE_DIALOG_CLOSED,
};


enum VALUE_DIALOG_VALUE_TYPE
{
    VALUE_TYPE_INT,
    VALUE_TYPE_FLOAT,
    VALUE_TYPE_STRING,
};

enum MAV_CUSTOM_MODE
{
    MAV_MODE_STABILIZE = 0,
    MAV_MODE_ACRO=1,
    MAV_MODE_ALT_HOLD=2,
    MAV_MODE_AUTO=3,
    MAV_MODE_GUIDED=4,
    MAV_MODE_LOITER=5,
    MAV_MODE_RTL=6,
    MAV_MODE_CIRCLE=7,
    MAV_MODE_LAND=9,
    MAV_MODE_DRIFT=11,
    MAV_MODE_SPORT=13,
    MAV_MODE_FLIP=14,
    MAV_MODE_AUTOTUNE=15,
    MAV_MODE_POS_HOLD=16,
    MAV_MODE_BRAKE=17,
    MAV_MODE_THROW=18,
    MAV_MODE_AVOID_ADSB=19,
    MAV_MODE_GUIDED_NO_GPS=20,
    MAV_MODE_SMART_RTL=21,
    MAV_MODE_FLOW_HOLD=22,
    MAV_MODE_FOLLOW=23,
    MAV_MODE_ZIGZAG=24,
    MAV_MODE_SYSTEM_ID=25,
    MAV_MODE_HELI_AUTOROTATE=26,
    MAV_MODE_AUTO_RTL=27,
};

//enum MAV_MODE
//{
//    MAV_MODE_STABILIZE = 0,
//    MAV_MODE_ACRO=1,
//    MAV_MODE_ALT_HOLD=2,
//    MAV_MODE_AUTO=3,
//    MAV_MODE_GUIDED=4,
//    MAV_MODE_LOITER=5,
//    MAV_MODE_RTL=6,
//    MAV_MODE_CIRCLE=7,
//    MAV_MODE_LAND=9,
//    MAV_MODE_DRIFT=11,
//    MAV_MODE_SPORT=13,
//    MAV_MODE_FLIP=14,
//    MAV_MODE_AUTOTUNE=15,
//    MAV_MODE_POS_HOLD=16,
//    MAV_MODE_BRAKE=17,
//    MAV_MODE_THROW=18,
//    MAV_MODE_AVOID_ADSB=19,
//    MAV_MODE_GUIDED_NO_GPS=20,
//    MAV_MODE_SMART_RTL=21,
//    MAV_MODE_FLOW_HOLD=22,
//    MAV_MODE_FOLLOW=23,
//    MAV_MODE_ZIGZAG=24,
//    MAV_MODE_SYSTEM_ID=25,
//    MAV_MODE_HELI_AUTOROTATE=26,
//    MAV_MODE_AUTO_RTL=27,
//};

const QMap<int,QString> MISSION_ITEMS = {
    {MAV_CMD_NAV_WAYPOINT, "WAYPOINT"},
//    1: Hold	Hold time. (ignored by fixed wing, time to stay at waypoint for rotary wing)	min:0	s
//    2: Accept Radius	Acceptance radius (if the sphere with this radius is hit, the waypoint counts as reached)	min:0	m
//    3: Pass Radius	0 to pass through the WP, if > 0 radius to pass by WP. Positive value for clockwise orbit, negative value for counter-clockwise orbit. Allows trajectory control.		m
//    4: Yaw	Desired yaw angle at waypoint (rotary wing). NaN to use the current system yaw heading mode (e.g. yaw towards next waypoint, yaw to home, etc.).		deg
//    5: Latitude	Latitude
//    6: Longitude	Longitude
//    7: Altitude	Altitude		m

    {MAV_CMD_NAV_RETURN_TO_LAUNCH, "RETURN_TO_LAUNCH"},
//    1	Empty
//    2	Empty
//    3	Empty
//    4	Empty
//    5	Empty
//    6	Empty
//    7	Empty

    {MAV_CMD_NAV_TAKEOFF, "TAKEOFF"},
//    1: Pitch	Minimum pitch (if airspeed sensor present), desired pitch without sensor	deg
//    2	Empty
//    3	Empty
//    4: Yaw	Yaw angle (if magnetometer present), ignored without magnetometer. NaN to use the current system yaw heading mode (e.g. yaw towards next waypoint, yaw to home, etc.).	deg
//    5: Latitude	Latitude
//    6: Longitude	Longitude
//    7: Altitude	Altitude	m

    {MAV_CMD_NAV_LAND, "LAND"},
//    1: Abort Alt	Minimum target altitude if landing is aborted (0 = undefined/use system default).		m
//    2: Land Mode	Precision land mode.	PRECISION_LAND_MODE
//    3	Empty.
//    4: Yaw Angle	Desired yaw angle. NaN to use the current system yaw heading mode (e.g. yaw towards next waypoint, yaw to home, etc.).		deg
//    5: Latitude	Latitude.
//    6: Longitude	Longitude.
//    7: Altitude	Landing altitude (ground level in current frame).		m

//    {MAV_CMD_NAV_LOITER_UNLIM, "LOITER_UNLIM"},
//    {MAV_CMD_NAV_LOITER_TURNS, "LOITER_TURNS"},
//    1: Turns	Number of turns.	min:0
//    2: Heading Required	Leave loiter circle only once heading towards the next waypoint (0 = False)	min:0 max:1 increment:1
//    3: Radius	Loiter radius around waypoint for forward-only moving vehicles (not multicopters). If positive loiter clockwise, else counter-clockwise		m
//    4: Xtrack Location	Loiter circle exit location and/or path to next waypoint ("xtrack") for forward-only moving vehicles (not multicopters). 0 for the vehicle to converge towards the center xtrack when it leaves the loiter (the line between the centers of the current and next waypoint), 1 to converge to the direct line between the location that the vehicle exits the loiter radius and the next waypoint. Otherwise the angle (in degrees) between the tangent of the loiter circle and the center xtrack at which the vehicle must leave the loiter (and converge to the center xtrack). NaN to use the current system default xtrack behaviour.
//    5: Latitude	Latitude
//    6: Longitude	Longitude
//    7: Altitude	Altitude		m

//    {MAV_CMD_NAV_LOITER_TIME, "LOITER_TIME"},
//    1: Time	Loiter time (only starts once Lat, Lon and Alt is reached).	min:0	s
//    2: Heading Required	Leave loiter circle only once heading towards the next waypoint (0 = False)	min:0 max:1 increment:1
//    3: Radius	Loiter radius around waypoint for forward-only moving vehicles (not multicopters). If positive loiter clockwise, else counter-clockwise.		m
//    4: Xtrack Location	Loiter circle exit location and/or path to next waypoint ("xtrack") for forward-only moving vehicles (not multicopters). 0 for the vehicle to converge towards the center xtrack when it leaves the loiter (the line between the centers of the current and next waypoint), 1 to converge to the direct line between the location that the vehicle exits the loiter radius and the next waypoint. Otherwise the angle (in degrees) between the tangent of the loiter circle and the center xtrack at which the vehicle must leave the loiter (and converge to the center xtrack). NaN to use the current system default xtrack behaviour.
//    5: Latitude	Latitude
//    6: Longitude	Longitude
//    7: Altitude	Altitude		m

//    {MAV_CMD_NAV_SPLINE_WAYPOINT, "SPLINE_WAYPOINT"},
//    {MAV_CMD_NAV_GUIDED_ENABLE, "GUIDED_ENABLE"},
    {MAV_CMD_NAV_DELAY, "DELAY"},
//    1: Delay	Delay (-1 to enable time-of-day fields)	min: -1 increment:1	s
//    2: Hour	hour (24h format, UTC, -1 to ignore)	min: -1 max:23 increment:1
//    3: Minute	minute (24h format, UTC, -1 to ignore)	min: -1 max:59 increment:1
//    4: Second	second (24h format, UTC, -1 to ignore)	min: -1 max:59 increment:1
//    5	Empty
//    6	Empty
//    7	Empty

//    {MAV_CMD_NAV_PAYLOAD_PLACE, "PAYLOAD_PLACE"},
//    {MAV_CMD_DO_JUMP, "DO_JUMP"},
//    {MAV_CMD_JUMP_TAG, "JUMP_TAG"},
//    {MAV_CMD_DO_JUMP_TAG, "DO_JUMP_TAG"},
//    {MAV_CMD_MISSION_START, "MISSION_START"},
//    {MAV_CMD_COMPONENT_ARM_DISARM, "COMPONENT_ARM_DISARM"},
//    {MAV_CMD_CONDITION_DELAY, "CONDITION_DELAY"},
//    {MAV_CMD_CONDITION_DISTANCE, "CONDITION_DISTANCE"},
//    {MAV_CMD_CONDITION_YAW, "CONDITION_YAW"},
//    {MAV_CMD_DO_AUX_FUNCTION, "DO_AUX_FUNCTION"},
//    {MAV_CMD_DO_CHANGE_SPEED, "DO_CHANGE_SPEED"},
//    1: Speed Type	Speed type of value set in param2 (such as airspeed, ground speed, and so on)	SPEED_TYPE
//    2: Speed	Speed (-1 indicates no change, -2 indicates return to default vehicle speed)	min: -2	m/s
//    3: Throttle	Throttle (-1 indicates no change, -2 indicates return to default vehicle throttle value)	min: -2	%
//    4	Reserved (set to 0)
//    5	Reserved (set to 0)
//    6	Reserved (set to 0)
//    7	Reserved (set to 0)

//    {MAV_CMD_DO_SET_HOME, "DO_SET_HOME"},
//    1: Use Current	Use current (1=use current location, 0=use specified location)	min:0 max:1 increment:1
//    2: Roll	Roll angle (of surface). Range: -180..180 degrees. NAN or 0 means value not set. 0.01 indicates zero roll.	min: -180 max:180	deg
//    3: Pitch	Pitch angle (of surface). Range: -90..90 degrees. NAN or 0 means value not set. 0.01 means zero pitch.	min: -90 max:90	deg
//    4: Yaw	Yaw angle. NaN to use default heading. Range: -180..180 degrees.	min: -180 max:180	deg
//    5: Latitude	Latitude
//    6: Longitude	Longitude
//    7: Altitude	Altitude		m

//    {MAV_CMD_DO_SET_SERVO, "DO_SET_SERVO"},
//    {MAV_CMD_DO_SET_RELAY, "DO_SET_RELAY"},
//    {MAV_CMD_DO_REPEAT_SERVO, "DO_REPEAT_SERVO"},
//    {MAV_CMD_DO_REPEAT_RELAY, "DO_REPEAT_RELAY"},
//    {MAV_CMD_DO_DIGICAM_CONFIGURE, "DO_DIGICAM_CONFIGURE"},
//    {MAV_CMD_DO_DIGICAM_CONTROL, "DO_DIGICAM_CONTROL"},
//    {MAV_CMD_DO_SET_CAM_TRIGG_DIST, "DO_SET_CAM_TRIGG_DIST"},
//    {MAV_CMD_DO_SET_ROI, "DO_SET_ROI"},
//    {MAV_CMD_DO_MOUNT_CONTROL, "DO_MOUNT_CONTROL"},
//    {MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW, "DO_GIMBAL_MANAGER_PITCHYAW"},
//    {MAV_CMD_DO_PARACHUTE, "DO_PARACHUTE"},
//    {MAV_CMD_DO_GRIPPER, "DO_GRIPPER"},
//    {MAV_CMD_DO_GUIDED_LIMITS, "DO_GUIDED_LIMITS"},
//    {MAV_CMD_DO_SET_RESUME_REPEAT_DIST, "DO_SET_RESUME_REPEAT_DIST"},
//    {MAV_CMD_DO_FENCE_ENABLE, "DO_FENCE_ENABLE"},
//    1: Enable	enable? (0=disable, 1=enable, 2=disable_floor_only)	min:0 max:2 increment:1
//    2	Empty
//    3	Empty
//    4	Empty
//    5	Empty
//    6	Empty
//    7	Empty

//    {MAV_CMD_DO_WINCH, "DO_WINCH"},
//    {MAV_CMD_STORAGE_FORMAT, "STORAGE_FORMAT"}
};
const QMap<int, QString> CUSTOM_MODES = {
    {MAV_MODE_STABILIZE,"Stabilize"},
    {MAV_MODE_ACRO,"Acro"},
    {MAV_MODE_ALT_HOLD,"AltHold"},
    {MAV_MODE_AUTO,"Auto"},
    {MAV_MODE_GUIDED,"Guided"},
    {MAV_MODE_LOITER,"Loiter"},
    {MAV_MODE_RTL,"RTL"},
    {MAV_MODE_CIRCLE,"Circle"},
    {MAV_MODE_LAND,"Land"},
    {MAV_MODE_DRIFT,"Drift"},
    {MAV_MODE_SPORT,"Sport"},
    {MAV_MODE_FLIP,"Flip"},
    {MAV_MODE_AUTOTUNE,"Autotune"},
    {MAV_MODE_POS_HOLD,"PosHold"},
    {MAV_MODE_BRAKE,"Brake"},
    {MAV_MODE_THROW,"Throw"},
    {MAV_MODE_AVOID_ADSB,"Avoid_ADSB"},
    {MAV_MODE_GUIDED_NO_GPS,"Guided_NoGPS"},
    {MAV_MODE_SMART_RTL,"Smart_RTL"},
    {MAV_MODE_FLOW_HOLD,"FlowHold"},
    {MAV_MODE_FOLLOW,"Follow"},
    {MAV_MODE_ZIGZAG,"ZigZag"},
    {MAV_MODE_SYSTEM_ID,"SystemID"},
    {MAV_MODE_HELI_AUTOROTATE,"Heli_Autorotate"},
    {MAV_MODE_AUTO_RTL,"Auto RTL"}
};

const QMap<int, QString> FLIGHT_MODES = {
    {MAV_MODE_PREFLIGHT,"Preflight"},
    {MAV_MODE_STABILIZE_ARMED,"Stabilize"},
    {MAV_MODE_MANUAL_ARMED,"Manual"},
    {MAV_MODE_GUIDED_ARMED,"Guided"},
    {MAV_MODE_AUTO_ARMED,"Auto"},
};
//typedef enum MAV_CMD_SPACECRAFT
//{
//    MAV_CMD_MISSION_PAUSE=6000,
//}MAV_CMD_SPACECRAFT;

const QMap<int, QString> SPECIAL_COMMANDS = {
    {MAV_GOTO_DO_CONTINUE ,"Прод. миссию"},
    {MAV_GOTO_HOLD_AT_CURRENT_POSITION,"Ост. на мест."},
    {MAV_GOTO_HOLD_AT_SPECIFIED_POSITION,"Ост. и заф."},
//    {MAV_MODE_ACRO,"Acro"},
//    {MAV_MODE_ALT_HOLD,"AltHold"},
//    {MAV_MODE_AUTO,"Auto"},
//    {MAV_MODE_GUIDED,"Guided"},
//    {MAV_MODE_LOITER,"Loiter"},
//    {MAV_MODE_RTL,"RTL"},
//    {MAV_MODE_CIRCLE,"Circle"},
//    {MAV_MODE_LAND,"Land"},
//    {MAV_MODE_DRIFT,"Drift"},
//    {MAV_MODE_SPORT,"Sport"},
//    {MAV_MODE_FLIP,"Flip"},
//    {MAV_MODE_AUTOTUNE,"Autotune"},
//    {MAV_MODE_POS_HOLD,"PosHold"},
//    {MAV_MODE_BRAKE,"Brake"},
//    {MAV_MODE_THROW,"Throw"},
//    {MAV_MODE_AVOID_ADSB,"Avoid_ADSB"},
//    {MAV_MODE_GUIDED_NO_GPS,"Guided_NoGPS"},
//    {MAV_MODE_SMART_RTL,"Smart_RTL"},
//    {MAV_MODE_FLOW_HOLD,"FlowHold"},
//    {MAV_MODE_FOLLOW,"Follow"},
//    {MAV_MODE_ZIGZAG,"ZigZag"},
//    {MAV_MODE_SYSTEM_ID,"SystemID"},
//    {MAV_MODE_HELI_AUTOROTATE,"Heli_Autorotate"},
//    {MAV_MODE_AUTO_RTL,"Auto RTL"}
};

const QMap<int, QString> SYSTEM_STATUSES = {

    {MAV_STATE_UNINIT, "UNINIT"},
    {MAV_STATE_BOOT, "BOOT"},
    {MAV_STATE_CALIBRATING, "CALIBRATING"},
    {MAV_STATE_STANDBY, "STANDBY"},
    {MAV_STATE_ACTIVE, "ACTIVE"},
    {MAV_STATE_CRITICAL, "CRITICAL"},
    {MAV_STATE_CRITICAL, "EMERGENCY"},
    {MAV_STATE_POWEROFF, "POWEROFF"},
    {MAV_STATE_FLIGHT_TERMINATION,	"FLT_TRMNTN"}
};


const QMap<int, QString> AVAILABLE_MESSAGES = {
    {MAVLINK_MSG_ID_HEARTBEAT,"HEARTBEAT"},
    {MAVLINK_MSG_ID_SYS_STATUS,"SYS_STATUS"},
    {MAVLINK_MSG_ID_SYSTEM_TIME,"SYSTEM_TIME"},
    {MAVLINK_MSG_ID_PING,"PING"},
    {MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL,"CHANGE_OPERATOR_CONTROL"},
    {MAVLINK_MSG_ID_CHANGE_OPERATOR_CONTROL_ACK,"CHANGE_OPERATOR_CONTROL_ACK"},
    {MAVLINK_MSG_ID_AUTH_KEY,"AUTH_KEY"},
    {MAVLINK_MSG_ID_LINK_NODE_STATUS,"LINK_NODE_STATUS"}, //WIP
    {MAVLINK_MSG_ID_SET_MODE,"SET_MODE"},
    {MAVLINK_MSG_ID_PARAM_REQUEST_READ,"PARAM_REQUEST_READ"},
    {MAVLINK_MSG_ID_PARAM_REQUEST_LIST,"PARAM_REQUEST_LIST"},
    {MAVLINK_MSG_ID_PARAM_VALUE,"PARAM_VALUE"},
    {MAVLINK_MSG_ID_PARAM_SET,"PARAM_SET"},
    {MAVLINK_MSG_ID_GPS_RAW_INT,"GPS_RAW_INT"},
    {MAVLINK_MSG_ID_GPS_STATUS,"GPS_STATUS"},
    {MAVLINK_MSG_ID_SCALED_IMU,"SCALED_IMU"},
    {MAVLINK_MSG_ID_RAW_IMU,"RAW_IMU"},
    {MAVLINK_MSG_ID_RAW_PRESSURE,"RAW_PRESSURE"},
    {MAVLINK_MSG_ID_SCALED_PRESSURE,"SCALED_PRESSURE"},
    {MAVLINK_MSG_ID_ATTITUDE,"ATTITUDE"},
    {MAVLINK_MSG_ID_ATTITUDE_QUATERNION,"ATTITUDE_QUATERNION"},
    {MAVLINK_MSG_ID_LOCAL_POSITION_NED,"LOCAL_POSITION_NED"},
    {MAVLINK_MSG_ID_GLOBAL_POSITION_INT,"GLOBAL_POSITION_INT"},
    {MAVLINK_MSG_ID_RC_CHANNELS_SCALED,"RC_CHANNELS_SCALED"},
    {MAVLINK_MSG_ID_RC_CHANNELS_RAW,"RC_CHANNELS_RAW"},
    {MAVLINK_MSG_ID_SERVO_OUTPUT_RAW,"SERVO_OUTPUT_RAW"},
    {MAVLINK_MSG_ID_MISSION_REQUEST_PARTIAL_LIST,"MISSION_REQUEST_PARTIAL_LIST"},
    {MAVLINK_MSG_ID_MISSION_WRITE_PARTIAL_LIST,"MISSION_WRITE_PARTIAL_LIST"},
    {MAVLINK_MSG_ID_MISSION_ITEM,"MISSION_ITEM"},
    {MAVLINK_MSG_ID_MISSION_REQUEST,"MISSION_REQUEST"},
    {MAVLINK_MSG_ID_MISSION_SET_CURRENT,"MISSION_SET_CURRENT"},
    {MAVLINK_MSG_ID_MISSION_CURRENT,"MISSION_CURRENT"},
    {MAVLINK_MSG_ID_MISSION_REQUEST_LIST,"MISSION_REQUEST_LIST"},
    {MAVLINK_MSG_ID_MISSION_COUNT,"MISSION_COUNT"},
    {MAVLINK_MSG_ID_MISSION_CLEAR_ALL,"MISSION_CLEAR_ALL"},
    {MAVLINK_MSG_ID_MISSION_ITEM_REACHED,"MISSION_ITEM_REACHED"},
    {MAVLINK_MSG_ID_MISSION_ACK,"MISSION_ACK"},
    {MAVLINK_MSG_ID_SET_GPS_GLOBAL_ORIGIN,"SET_GPS_GLOBAL_ORIGIN"},
    {MAVLINK_MSG_ID_GPS_GLOBAL_ORIGIN,"GPS_GLOBAL_ORIGIN"},
    {MAVLINK_MSG_ID_PARAM_MAP_RC,"PARAM_MAP_RC"},
    {MAVLINK_MSG_ID_MISSION_REQUEST_INT,"MISSION_REQUEST_INT"},
    {MAVLINK_MSG_ID_SAFETY_SET_ALLOWED_AREA,"SAFETY_SET_ALLOWED_AREA"},
    {MAVLINK_MSG_ID_SAFETY_ALLOWED_AREA,"SAFETY_ALLOWED_AREA"},
    {MAVLINK_MSG_ID_ATTITUDE_QUATERNION_COV,"ATTITUDE_QUATERNION_COV"},
    {MAVLINK_MSG_ID_NAV_CONTROLLER_OUTPUT,"NAV_CONTROLLER_OUTPUT"},
    {MAVLINK_MSG_ID_GLOBAL_POSITION_INT_COV,"GLOBAL_POSITION_INT_COV"},
    {MAVLINK_MSG_ID_LOCAL_POSITION_NED_COV,"LOCAL_POSITION_NED_COV"},
    {MAVLINK_MSG_ID_RC_CHANNELS,"RC_CHANNELS"},
    {MAVLINK_MSG_ID_REQUEST_DATA_STREAM,"REQUEST_DATA_STREAM"},
    {MAVLINK_MSG_ID_DATA_STREAM,"DATA_STREAM"},
    {MAVLINK_MSG_ID_MANUAL_CONTROL,"MANUAL_CONTROL"},
    {MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE,"RC_CHANNELS_OVERRIDE"},
    {MAVLINK_MSG_ID_MISSION_ITEM_INT,"MISSION_ITEM_INT"},
    {MAVLINK_MSG_ID_VFR_HUD,"VFR_HUD"},
    {MAVLINK_MSG_ID_COMMAND_INT,"COMMAND_INT"},
    {MAVLINK_MSG_ID_COMMAND_LONG,"COMMAND_LONG"},
    {MAVLINK_MSG_ID_COMMAND_ACK,"COMMAND_ACK"},
    {MAVLINK_MSG_ID_COMMAND_CANCEL,"COMMAND_CANCEL"},
    {MAVLINK_MSG_ID_MANUAL_SETPOINT,"MANUAL_SETPOINT"},
    {MAVLINK_MSG_ID_SET_ATTITUDE_TARGET,"SET_ATTITUDE_TARGET"},
    {MAVLINK_MSG_ID_ATTITUDE_TARGET,"ATTITUDE_TARGET"},
    {MAVLINK_MSG_ID_SET_POSITION_TARGET_LOCAL_NED,"SET_POSITION_TARGET_LOCAL_NED"},
    {MAVLINK_MSG_ID_POSITION_TARGET_LOCAL_NED,"POSITION_TARGET_LOCAL_NED"},
    {MAVLINK_MSG_ID_SET_POSITION_TARGET_GLOBAL_INT,"SET_POSITION_TARGET_GLOBAL_INT"},
    {MAVLINK_MSG_ID_POSITION_TARGET_GLOBAL_INT,"POSITION_TARGET_GLOBAL_INT"},
    {MAVLINK_MSG_ID_LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET,"LOCAL_POSITION_NED_SYSTEM_GLOBAL_OFFSET"},
    {MAVLINK_MSG_ID_HIL_STATE,"HIL_STATE"},
    {MAVLINK_MSG_ID_HIL_CONTROLS,"HIL_CONTROLS"},
    {MAVLINK_MSG_ID_HIL_RC_INPUTS_RAW,"HIL_RC_INPUTS_RAW"},
    {MAVLINK_MSG_ID_HIL_ACTUATOR_CONTROLS,"HIL_ACTUATOR_CONTROLS"},
    {MAVLINK_MSG_ID_OPTICAL_FLOW,"OPTICAL_FLOW"},
    {MAVLINK_MSG_ID_GLOBAL_VISION_POSITION_ESTIMATE,"GLOBAL_VISION_POSITION_ESTIMATE"},
    {MAVLINK_MSG_ID_VISION_POSITION_ESTIMATE,"VISION_POSITION_ESTIMATE"},
    {MAVLINK_MSG_ID_VISION_SPEED_ESTIMATE,"VISION_SPEED_ESTIMATE"},
    {MAVLINK_MSG_ID_VICON_POSITION_ESTIMATE,"VICON_POSITION_ESTIMATE"},
    {MAVLINK_MSG_ID_HIGHRES_IMU,"HIGHRES_IMU"},
    {MAVLINK_MSG_ID_OPTICAL_FLOW_RAD,"OPTICAL_FLOW_RAD"},
    {MAVLINK_MSG_ID_HIL_SENSOR,"HIL_SENSOR"},
    {MAVLINK_MSG_ID_SIM_STATE,"SIM_STATE"},
    {MAVLINK_MSG_ID_RADIO_STATUS,"RADIO_STATUS"},
    {MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL,"FILE_TRANSFER_PROTOCOL"},
    {MAVLINK_MSG_ID_TIMESYNC,"TIMESYNC"},
    {MAVLINK_MSG_ID_CAMERA_TRIGGER,"CAMERA_TRIGGER"},
    {MAVLINK_MSG_ID_HIL_GPS,"HIL_GPS"},
    {MAVLINK_MSG_ID_HIL_OPTICAL_FLOW,"HIL_OPTICAL_FLOW"},
    {MAVLINK_MSG_ID_HIL_STATE_QUATERNION,"HIL_STATE_QUATERNION"},
    {MAVLINK_MSG_ID_SCALED_IMU2,"SCALED_IMU2"},
    {MAVLINK_MSG_ID_LOG_REQUEST_LIST,"LOG_REQUEST_LIST"},
    {MAVLINK_MSG_ID_LOG_ENTRY,"LOG_ENTRY"},
    {MAVLINK_MSG_ID_LOG_REQUEST_DATA,"LOG_REQUEST_DATA"},
    {MAVLINK_MSG_ID_LOG_DATA,"LOG_DATA"},
    {MAVLINK_MSG_ID_LOG_ERASE,"LOG_ERASE"},
    {MAVLINK_MSG_ID_LOG_REQUEST_END,"LOG_REQUEST_END"},
    {MAVLINK_MSG_ID_GPS_INJECT_DATA,"GPS_INJECT_DATA"},
    {MAVLINK_MSG_ID_GPS2_RAW,"GPS2_RAW"},
    {MAVLINK_MSG_ID_POWER_STATUS,"POWER_STATUS"},
    {MAVLINK_MSG_ID_SERIAL_CONTROL,"SERIAL_CONTROL"},
    {MAVLINK_MSG_ID_GPS_RTK,"GPS_RTK"},
    {MAVLINK_MSG_ID_GPS2_RTK,"GPS2_RTK"},
    {MAVLINK_MSG_ID_SCALED_IMU3,"SCALED_IMU3"},
    {MAVLINK_MSG_ID_DATA_TRANSMISSION_HANDSHAKE,"DATA_TRANSMISSION_HANDSHAKE"},
    {MAVLINK_MSG_ID_ENCAPSULATED_DATA,"ENCAPSULATED_DATA"},
    {MAVLINK_MSG_ID_DISTANCE_SENSOR,"DISTANCE_SENSOR"},
    {MAVLINK_MSG_ID_TERRAIN_REQUEST,"TERRAIN_REQUEST"},
    {MAVLINK_MSG_ID_TERRAIN_DATA,"TERRAIN_DATA"},
    {MAVLINK_MSG_ID_TERRAIN_CHECK,"TERRAIN_CHECK"},
    {MAVLINK_MSG_ID_TERRAIN_REPORT,"TERRAIN_REPORT"},
    {MAVLINK_MSG_ID_SCALED_PRESSURE2,"SCALED_PRESSURE2"},
    {MAVLINK_MSG_ID_ATT_POS_MOCAP,"ATT_POS_MOCAP"},
    {MAVLINK_MSG_ID_SET_ACTUATOR_CONTROL_TARGET,"SET_ACTUATOR_CONTROL_TARGET"},
    {MAVLINK_MSG_ID_ACTUATOR_CONTROL_TARGET,"ACTUATOR_CONTROL_TARGET"},
    {MAVLINK_MSG_ID_ALTITUDE,"ALTITUDE"},
    {MAVLINK_MSG_ID_RESOURCE_REQUEST,"RESOURCE_REQUEST"},
    {MAVLINK_MSG_ID_SCALED_PRESSURE3,"SCALED_PRESSURE3"},
    {MAVLINK_MSG_ID_FOLLOW_TARGET,"FOLLOW_TARGET"},
    {MAVLINK_MSG_ID_CONTROL_SYSTEM_STATE,"CONTROL_SYSTEM_STATE"},
    {MAVLINK_MSG_ID_BATTERY_STATUS,"BATTERY_STATUS"},
    {MAVLINK_MSG_ID_AUTOPILOT_VERSION,"AUTOPILOT_VERSION"},
    {MAVLINK_MSG_ID_LANDING_TARGET,"LANDING_TARGET"},
    {MAVLINK_MSG_ID_FENCE_STATUS,"FENCE_STATUS"},
    {MAVLINK_MSG_ID_MAG_CAL_REPORT,"MAG_CAL_REPORT"},
    {MAVLINK_MSG_ID_EFI_STATUS,"EFI_STATUS"},
    {MAVLINK_MSG_ID_ESTIMATOR_STATUS,"ESTIMATOR_STATUS"},
    {MAVLINK_MSG_ID_WIND_COV,"WIND_COV"},
    {MAVLINK_MSG_ID_GPS_INPUT,"GPS_INPUT"},
    {MAVLINK_MSG_ID_GPS_RTCM_DATA,"GPS_RTCM_DATA"},
    {MAVLINK_MSG_ID_HIGH_LATENCY,"HIGH_LATENCY"},
    {MAVLINK_MSG_ID_HIGH_LATENCY2,"HIGH_LATENCY2"},
    {MAVLINK_MSG_ID_VIBRATION,"VIBRATION"},
    {MAVLINK_MSG_ID_HOME_POSITION,"HOME_POSITION"},
    {MAVLINK_MSG_ID_SET_HOME_POSITION,"SET_HOME_POSITION"},
    {MAVLINK_MSG_ID_MESSAGE_INTERVAL,"MESSAGE_INTERVAL"},
    {MAVLINK_MSG_ID_EXTENDED_SYS_STATE,"EXTENDED_SYS_STATE"},
    {MAVLINK_MSG_ID_ADSB_VEHICLE,"ADSB_VEHICLE"},
    {MAVLINK_MSG_ID_COLLISION,"COLLISION"},
    {MAVLINK_MSG_ID_V2_EXTENSION,"V2_EXTENSION"},
    {MAVLINK_MSG_ID_MEMORY_VECT,"MEMORY_VECT"},
    {MAVLINK_MSG_ID_DEBUG_VECT,"DEBUG_VECT"},
    {MAVLINK_MSG_ID_NAMED_VALUE_FLOAT,"NAMED_VALUE_FLOAT"},
    {MAVLINK_MSG_ID_NAMED_VALUE_INT,"NAMED_VALUE_INT"},
    {MAVLINK_MSG_ID_STATUSTEXT,"STATUSTEXT"},
    {MAVLINK_MSG_ID_DEBUG,"DEBUG"},
    {MAVLINK_MSG_ID_SETUP_SIGNING,"SETUP_SIGNING"},
    {MAVLINK_MSG_ID_BUTTON_CHANGE,"BUTTON_CHANGE"},
    {MAVLINK_MSG_ID_PLAY_TUNE,"PLAY_TUNE"},
    {MAVLINK_MSG_ID_CAMERA_INFORMATION,"CAMERA_INFORMATION"},
    {MAVLINK_MSG_ID_CAMERA_SETTINGS,"CAMERA_SETTINGS"},
    {MAVLINK_MSG_ID_STORAGE_INFORMATION,"STORAGE_INFORMATION"},
    {MAVLINK_MSG_ID_CAMERA_CAPTURE_STATUS,"CAMERA_CAPTURE_STATUS"},
    {MAVLINK_MSG_ID_CAMERA_IMAGE_CAPTURED,"CAMERA_IMAGE_CAPTURED"},
    {MAVLINK_MSG_ID_FLIGHT_INFORMATION,"FLIGHT_INFORMATION"},
    {MAVLINK_MSG_ID_MOUNT_ORIENTATION,"MOUNT_ORIENTATION"},
    {MAVLINK_MSG_ID_LOGGING_DATA,"LOGGING_DATA"},
    {MAVLINK_MSG_ID_LOGGING_DATA_ACKED,"LOGGING_DATA_ACKED"},
    {MAVLINK_MSG_ID_LOGGING_ACK,"LOGGING_ACK"},
    {MAVLINK_MSG_ID_VIDEO_STREAM_INFORMATION,"VIDEO_STREAM_INFORMATION"},
    {MAVLINK_MSG_ID_VIDEO_STREAM_STATUS,"VIDEO_STREAM_STATUS"},
    {MAVLINK_MSG_ID_CAMERA_FOV_STATUS,"CAMERA_FOV_STATUS"},
    {MAVLINK_MSG_ID_CAMERA_TRACKING_IMAGE_STATUS,"CAMERA_TRACKING_IMAGE_STATUS"},
    {MAVLINK_MSG_ID_CAMERA_TRACKING_GEO_STATUS,"CAMERA_TRACKING_GEO_STATUS"},
    {MAVLINK_MSG_ID_GIMBAL_MANAGER_INFORMATION,"GIMBAL_MANAGER_INFORMATION"},
    {MAVLINK_MSG_ID_GIMBAL_MANAGER_STATUS,"GIMBAL_MANAGER_STATUS"},
    {MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_ATTITUDE,"GIMBAL_MANAGER_SET_ATTITUDE"},
    {MAVLINK_MSG_ID_GIMBAL_DEVICE_INFORMATION,"GIMBAL_DEVICE_INFORMATION"},
    {MAVLINK_MSG_ID_GIMBAL_DEVICE_SET_ATTITUDE,"GIMBAL_DEVICE_SET_ATTITUDE"},
    {MAVLINK_MSG_ID_GIMBAL_DEVICE_ATTITUDE_STATUS,"GIMBAL_DEVICE_ATTITUDE_STATUS"},
    {MAVLINK_MSG_ID_AUTOPILOT_STATE_FOR_GIMBAL_DEVICE,"AUTOPILOT_STATE_FOR_GIMBAL_DEVICE"},
    {MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_PITCHYAW,"GIMBAL_MANAGER_SET_PITCHYAW"},
    {MAVLINK_MSG_ID_GIMBAL_MANAGER_SET_MANUAL_CONTROL,"GIMBAL_MANAGER_SET_MANUAL_CONTROL"},
    {MAVLINK_MSG_ID_ESC_INFO,"ESC_INFO"},
    {MAVLINK_MSG_ID_ESC_STATUS,"ESC_STATUS"},
    {MAVLINK_MSG_ID_WIFI_CONFIG_AP,"WIFI_CONFIG_AP"},
    {MAVLINK_MSG_ID_AIS_VESSEL,"AIS_VESSEL"},
    {MAVLINK_MSG_ID_UAVCAN_NODE_STATUS,"UAVCAN_NODE_STATUS"},
    {MAVLINK_MSG_ID_UAVCAN_NODE_INFO,"UAVCAN_NODE_INFO"},
    {MAVLINK_MSG_ID_PARAM_EXT_REQUEST_READ,"PARAM_EXT_REQUEST_READ"},
    {MAVLINK_MSG_ID_PARAM_EXT_REQUEST_LIST,"PARAM_EXT_REQUEST_LIST"},
    {MAVLINK_MSG_ID_PARAM_EXT_VALUE,"PARAM_EXT_VALUE"},
    {MAVLINK_MSG_ID_PARAM_EXT_SET,"PARAM_EXT_SET"},
    {MAVLINK_MSG_ID_PARAM_EXT_ACK,"PARAM_EXT_ACK"},
    {MAVLINK_MSG_ID_OBSTACLE_DISTANCE,"OBSTACLE_DISTANCE"},
    {MAVLINK_MSG_ID_ODOMETRY,"ODOMETRY"},
    {MAVLINK_MSG_ID_TRAJECTORY_REPRESENTATION_WAYPOINTS,"TRAJECTORY_REPRESENTATION_WAYPOINTS"},
    {MAVLINK_MSG_ID_TRAJECTORY_REPRESENTATION_BEZIER,"TRAJECTORY_REPRESENTATION_BEZIER"},
    {MAVLINK_MSG_ID_CELLULAR_STATUS,"CELLULAR_STATUS"},
    {MAVLINK_MSG_ID_ISBD_LINK_STATUS,"ISBD_LINK_STATUS"},
    {MAVLINK_MSG_ID_CELLULAR_CONFIG,"CELLULAR_CONFIG"},
    {MAVLINK_MSG_ID_RAW_RPM,"RAW_RPM"},
    {MAVLINK_MSG_ID_UTM_GLOBAL_POSITION,"UTM_GLOBAL_POSITION"},
    {MAVLINK_MSG_ID_DEBUG_FLOAT_ARRAY,"DEBUG_FLOAT_ARRAY"},
    {MAVLINK_MSG_ID_ORBIT_EXECUTION_STATUS,"ORBIT_EXECUTION_STATUS"},
    {MAVLINK_MSG_ID_SMART_BATTERY_INFO,"SMART_BATTERY_INFO"},
    {MAVLINK_MSG_ID_GENERATOR_STATUS,"GENERATOR_STATUS"},
    {MAVLINK_MSG_ID_ACTUATOR_OUTPUT_STATUS,"ACTUATOR_OUTPUT_STATUS"},
    {MAVLINK_MSG_ID_TIME_ESTIMATE_TO_TARGET,"TIME_ESTIMATE_TO_TARGET"},
    {MAVLINK_MSG_ID_TUNNEL,"TUNNEL"},
    {MAVLINK_MSG_ID_CAN_FRAME,"CAN_FRAME"},
    {MAVLINK_MSG_ID_ONBOARD_COMPUTER_STATUS,"ONBOARD_COMPUTER_STATUS"},
    {MAVLINK_MSG_ID_COMPONENT_INFORMATION,"COMPONENT_INFORMATION"},
    {MAVLINK_MSG_ID_COMPONENT_METADATA,"COMPONENT_METADATA"},
    {MAVLINK_MSG_ID_PLAY_TUNE_V2,"PLAY_TUNE_V2"},
    {MAVLINK_MSG_ID_SUPPORTED_TUNES,"SUPPORTED_TUNES"},
    {MAVLINK_MSG_ID_EVENT,"EVENT"},
    {MAVLINK_MSG_ID_CURRENT_EVENT_SEQUENCE,"CURRENT_EVENT_SEQUENCE"},
    {MAVLINK_MSG_ID_REQUEST_EVENT,"REQUEST_EVENT"},
    {MAVLINK_MSG_ID_RESPONSE_EVENT_ERROR,"RESPONSE_EVENT_ERROR"},
    {MAVLINK_MSG_ID_CANFD_FRAME,"CANFD_FRAME"},
    {MAVLINK_MSG_ID_CAN_FILTER_MODIFY,"CAN_FILTER_MODIFY"},
    {MAVLINK_MSG_ID_WHEEL_DISTANCE,"WHEEL_DISTANCE"},
    {MAVLINK_MSG_ID_WINCH_STATUS,"WINCH_STATUS"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_BASIC_ID,"OPEN_DRONE_ID_BASIC_ID"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_LOCATION,"OPEN_DRONE_ID_LOCATION"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_AUTHENTICATION,"OPEN_DRONE_ID_AUTHENTICATION"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_SELF_ID,"OPEN_DRONE_ID_SELF_ID"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_SYSTEM,"OPEN_DRONE_ID_SYSTEM"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_OPERATOR_ID,"OPEN_DRONE_ID_OPERATOR_ID"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_MESSAGE_PACK,"OPEN_DRONE_ID_MESSAGE_PACK"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_ARM_STATUS,"OPEN_DRONE_ID_ARM_STATUS"},
    {MAVLINK_MSG_ID_OPEN_DRONE_ID_SYSTEM_UPDATE,"OPEN_DRONE_ID_SYSTEM_UPDATE"},
    {MAVLINK_MSG_ID_HYGROMETER_SENSOR,"HYGROMETER_SENSOR"},
        // ARDUPILOTMEGA
    {MAVLINK_MSG_ID_MEMINFO,"MEMINFO"},
    {MAVLINK_MSG_ID_EKF_STATUS_REPORT,"EKF_STATUS_REPORT"},
    {MAVLINK_MSG_ID_HWSTATUS,"HWSTATUS"},
    {MAVLINK_MSG_ID_AHRS,"AHRS"},
    {MAVLINK_MSG_ID_AHRS2,"AHRS2"},
    {MAVLINK_MSG_ID_AHRS3,"AHRS3"},
    {MAVLINK_MSG_ID_SIMSTATE,"SIMSTATE"},
    {MAVLINK_MSG_ID_SENSOR_OFFSETS,"SENSOR_OFFSETS"},
};
const QMap<int, QString> availableCommands = {
    {MAV_CMD_NAV_WAYPOINT,"NAV_WAYPOINT"},
    {MAV_CMD_NAV_LOITER_UNLIM,"NAV_LOITER_UNLIM"},
    {MAV_CMD_NAV_LOITER_TURNS,"NAV_LOITER_TURNS"},
    {MAV_CMD_NAV_LOITER_TIME,"NAV_LOITER_TIME"},
    {MAV_CMD_NAV_RETURN_TO_LAUNCH,"NAV_RETURN_TO_LAUNCH"},
    {MAV_CMD_NAV_LAND,"NAV_LAND"},
    {MAV_CMD_NAV_TAKEOFF,"NAV_TAKEOFF"},
    {MAV_CMD_NAV_LAND_LOCAL,"NAV_LAND_LOCAL"},
    {MAV_CMD_NAV_TAKEOFF_LOCAL ,"NAV_TAKEOFF_LOCAL"},
    {MAV_CMD_NAV_FOLLOW,"NAV_FOLLOW"},
    {MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT,"NAV_CONTINUE_AND_CHANGE_ALT"},
    {MAV_CMD_NAV_LOITER_TO_ALT,"NAV_LOITER_TO_ALT"},
    {MAV_CMD_DO_FOLLOW,"DO_FOLLOW"},
    {MAV_CMD_DO_FOLLOW_REPOSITION,"DO_FOLLOW_REPOSITION"},
    {MAV_CMD_DO_ORBIT ,"DO_ORBIT"},
    {MAV_CMD_NAV_ROI,"NAV_ROI"},
    {MAV_CMD_NAV_PATHPLANNING,"NAV_PATHPLANNING"},
    {MAV_CMD_NAV_SPLINE_WAYPOINT,"NAV_SPLINE_WAYPOINT"},
    {MAV_CMD_NAV_VTOL_TAKEOFF ,"NAV_VTOL_TAKEOFF"},
    {MAV_CMD_NAV_VTOL_LAND,"NAV_VTOL_LAND"},
    {MAV_CMD_NAV_GUIDED_ENABLE,"NAV_GUIDED_ENABLE"},
    {MAV_CMD_NAV_DELAY,"NAV_DELAY"},
    {MAV_CMD_NAV_PAYLOAD_PLACE,"NAV_PAYLOAD_PLACE"},
    {MAV_CMD_NAV_LAST,"NAV_LAST"},
    {MAV_CMD_CONDITION_DELAY ,"CONDITION_DELAY"},
    {MAV_CMD_CONDITION_CHANGE_ALT ,"CONDITION_CHANGE_ALT"},
    {MAV_CMD_CONDITION_DISTANCE,"CONDITION_DISTANCE"},
    {MAV_CMD_CONDITION_YAW ,"CONDITION_YAW"},
    {MAV_CMD_CONDITION_LAST,"CONDITION_LAST"},
    {MAV_CMD_DO_SET_MODE,"DO_SET_MODE"},
    {MAV_CMD_DO_JUMP,"DO_JUMP"},
    {MAV_CMD_DO_CHANGE_SPEED,"DO_CHANGE_SPEED"},
    {MAV_CMD_DO_SET_HOME,"DO_SET_HOME"},
    {MAV_CMD_DO_SET_PARAMETER,"DO_SET_PARAMETER"},
    {MAV_CMD_DO_SET_RELAY ,"DO_SET_RELAY"},
    {MAV_CMD_DO_REPEAT_RELAY ,"DO_REPEAT_RELAY"},
    {MAV_CMD_DO_SET_SERVO,"DO_SET_SERVO"},
    {MAV_CMD_DO_REPEAT_SERVO,"DO_REPEAT_SERVO"},
    {MAV_CMD_DO_FLIGHTTERMINATION,"DO_FLIGHTTERMINATION"},
    {MAV_CMD_DO_CHANGE_ALTITUDE ,"DO_CHANGE_ALTITUDE"},
    {MAV_CMD_DO_SET_ACTUATOR,"DO_SET_ACTUATOR"},
    {MAV_CMD_DO_LAND_START ,"DO_LAND_START"},
    {MAV_CMD_DO_RALLY_LAND,"DO_RALLY_LAND"},
    {MAV_CMD_DO_GO_AROUND,"DO_GO_AROUND"},
    {MAV_CMD_DO_REPOSITION,"DO_REPOSITION"},
    {MAV_CMD_DO_PAUSE_CONTINUE,"DO_PAUSE_CONTINUE"},
    {MAV_CMD_DO_SET_REVERSE,"DO_SET_REVERSE"},
    {MAV_CMD_DO_SET_ROI_LOCATION,"DO_SET_ROI_LOCATION"},
    {MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET,"DO_SET_ROI_WPNEXT_OFFSET"},
    {MAV_CMD_DO_SET_ROI_NONE,"DO_SET_ROI_NONE"},
    {MAV_CMD_DO_SET_ROI_SYSID,"DO_SET_ROI_SYSID"},
    {MAV_CMD_DO_CONTROL_VIDEO,"DO_CONTROL_VIDEO"},
    {MAV_CMD_DO_SET_ROI,"DO_SET_ROI"},
    {MAV_CMD_DO_DIGICAM_CONFIGURE ,"DO_DIGICAM_CONFIGURE"},
    {MAV_CMD_DO_DIGICAM_CONTROL,"DO_DIGICAM_CONTROL"},
    {MAV_CMD_DO_MOUNT_CONFIGURE,"DO_MOUNT_CONFIGURE"},
    {MAV_CMD_DO_MOUNT_CONTROL,"DO_MOUNT_CONTROL"},
    {MAV_CMD_DO_SET_CAM_TRIGG_DIST,"DO_SET_CAM_TRIGG_DIST"},
    {MAV_CMD_DO_FENCE_ENABLE,"DO_FENCE_ENABLE"},
    {MAV_CMD_DO_PARACHUTE,"DO_PARACHUTE"},
    {MAV_CMD_DO_MOTOR_TEST,"DO_MOTOR_TEST"},
    {MAV_CMD_DO_INVERTED_FLIGHT,"DO_INVERTED_FLIGHT"},
    {MAV_CMD_DO_GRIPPER,"DO_GRIPPER"},
    {MAV_CMD_DO_AUTOTUNE_ENABLE,"DO_AUTOTUNE_ENABLE"},
    {MAV_CMD_NAV_SET_YAW_SPEED,"NAV_SET_YAW_SPEED"},
    {MAV_CMD_DO_SET_CAM_TRIGG_INTERVAL,"DO_SET_CAM_TRIGG_INTERVAL"},
    {MAV_CMD_DO_MOUNT_CONTROL_QUAT,"DO_MOUNT_CONTROL_QUAT"},
    {MAV_CMD_DO_GUIDED_MASTER,"DO_GUIDED_MASTER"},
    {MAV_CMD_DO_GUIDED_LIMITS,"DO_GUIDED_LIMITS"},
    {MAV_CMD_DO_ENGINE_CONTROL,"DO_ENGINE_CONTROL"},
    {MAV_CMD_DO_SET_MISSION_CURRENT ,"DO_SET_MISSION_CURRENT"},
    {MAV_CMD_DO_LAST,"DO_LAST"},
    {MAV_CMD_PREFLIGHT_CALIBRATION ,"PREFLIGHT_CALIBRATION"},
    {MAV_CMD_PREFLIGHT_SET_SENSOR_OFFSETS,"PREFLIGHT_SET_SENSOR_OFFSETS"},
    {MAV_CMD_PREFLIGHT_UAVCAN,"PREFLIGHT_UAVCAN"},
    {MAV_CMD_PREFLIGHT_STORAGE,"PREFLIGHT_STORAGE"},
    {MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN,"PREFLIGHT_REBOOT_SHUTDOWN"},
    {MAV_CMD_OVERRIDE_GOTO,"OVERRIDE_GOTO"},
    {MAV_CMD_OBLIQUE_SURVEY,"OBLIQUE_SURVEY"},
    {MAV_CMD_MISSION_START,"MISSION_START"},
    {MAV_CMD_ACTUATOR_TEST,"ACTUATOR_TEST"},
    {MAV_CMD_CONFIGURE_ACTUATOR,"CONFIGURE_ACTUATOR"},
    {MAV_CMD_COMPONENT_ARM_DISARM,"COMPONENT_ARM_DISARM"},
    {MAV_CMD_RUN_PREARM_CHECKS,"RUN_PREARM_CHECKS"},
    {MAV_CMD_ILLUMINATOR_ON_OFF,"ILLUMINATOR_ON_OFF"},
    {MAV_CMD_GET_HOME_POSITION,"GET_HOME_POSITION"},
    {MAV_CMD_INJECT_FAILURE,"INJECT_FAILURE"},
    {MAV_CMD_START_RX_PAIR,"START_RX_PAIR"},
    {MAV_CMD_GET_MESSAGE_INTERVAL,"GET_MESSAGE_INTERVAL"},
    {MAV_CMD_SET_MESSAGE_INTERVAL ,"SET_MESSAGE_INTERVAL"},
    {MAV_CMD_REQUEST_MESSAGE,"REQUEST_MESSAGE"},
    {MAV_CMD_REQUEST_PROTOCOL_VERSION,"REQUEST_PROTOCOL_VERSION"},
    {MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES,"REQUEST_AUTOPILOT_CAPABILITIES"},
    {MAV_CMD_REQUEST_CAMERA_INFORMATION,"REQUEST_CAMERA_INFORMATION"},
    {MAV_CMD_REQUEST_CAMERA_SETTINGS,"REQUEST_CAMERA_SETTINGS"},
    {MAV_CMD_REQUEST_STORAGE_INFORMATION,"REQUEST_STORAGE_INFORMATION"},
    {MAV_CMD_STORAGE_FORMAT,"STORAGE_FORMAT"},
    {MAV_CMD_REQUEST_CAMERA_CAPTURE_STATUS,"REQUEST_CAMERA_CAPTURE_STATUS"},
    {MAV_CMD_REQUEST_FLIGHT_INFORMATION,"REQUEST_FLIGHT_INFORMATION"},
    {MAV_CMD_RESET_CAMERA_SETTINGS,"RESET_CAMERA_SETTINGS"},
    {MAV_CMD_SET_CAMERA_MODE,"SET_CAMERA_MODE"},
    {MAV_CMD_SET_CAMERA_ZOOM,"SET_CAMERA_ZOOM"},
    {MAV_CMD_SET_CAMERA_FOCUS,"SET_CAMERA_FOCUS"},
    {MAV_CMD_SET_STORAGE_USAGE,"SET_STORAGE_USAGE"},
    {MAV_CMD_JUMP_TAG,"JUMP_TAG"},
    {MAV_CMD_DO_JUMP_TAG ,"DO_JUMP_TAG"},
    {MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW,"DO_GIMBAL_MANAGER_PITCHYAW"},
    {MAV_CMD_DO_GIMBAL_MANAGER_CONFIGURE,"DO_GIMBAL_MANAGER_CONFIGURE"},
    {MAV_CMD_IMAGE_START_CAPTURE,"IMAGE_START_CAPTURE"},
    {MAV_CMD_IMAGE_STOP_CAPTURE,"IMAGE_STOP_CAPTURE"},
    {MAV_CMD_REQUEST_CAMERA_IMAGE_CAPTURE,"REQUEST_CAMERA_IMAGE_CAPTURE"},
    {MAV_CMD_DO_TRIGGER_CONTROL,"DO_TRIGGER_CONTROL"},
    {MAV_CMD_CAMERA_TRACK_POINT,"CAMERA_TRACK_POINT"},
    {MAV_CMD_CAMERA_TRACK_RECTANGLE,"CAMERA_TRACK_RECTANGLE"},
    {MAV_CMD_CAMERA_STOP_TRACKING,"CAMERA_STOP_TRACKING"},
    {MAV_CMD_VIDEO_START_CAPTURE, "VIDEO_START_CAPTURE"},
    {MAV_CMD_VIDEO_STOP_CAPTURE,"VIDEO_STOP_CAPTURE"},
    {MAV_CMD_VIDEO_START_STREAMING,"VIDEO_START_STREAMING"},
    {MAV_CMD_VIDEO_STOP_STREAMING,"VIDEO_STOP_STREAMING"},
    {MAV_CMD_REQUEST_VIDEO_STREAM_INFORMATION,"REQUEST_VIDEO_STREAM_INFORMATION"},
    {MAV_CMD_REQUEST_VIDEO_STREAM_STATUS,"REQUEST_VIDEO_STREAM_STATUS"},
    {MAV_CMD_LOGGING_START,"LOGGING_START"},
    {MAV_CMD_LOGGING_STOP,"LOGGING_STOP"},
    {MAV_CMD_AIRFRAME_CONFIGURATION,"AIRFRAME_CONFIGURATION"},
    {MAV_CMD_CONTROL_HIGH_LATENCY,"CONTROL_HIGH_LATENCY"},
    {MAV_CMD_PANORAMA_CREATE,"PANORAMA_CREATE"},
    {MAV_CMD_DO_VTOL_TRANSITION,"DO_VTOL_TRANSITION"},
    {MAV_CMD_ARM_AUTHORIZATION_REQUEST ,"ARM_AUTHORIZATION_REQUEST"},
    {MAV_CMD_SET_GUIDED_SUBMODE_STANDARD,"SET_GUIDED_SUBMODE_STANDARD"},
    {MAV_CMD_SET_GUIDED_SUBMODE_CIRCLE,"SET_GUIDED_SUBMODE_CIRCLE"},
    {MAV_CMD_CONDITION_GATE,"CONDITION_GATE"},
    {MAV_CMD_NAV_FENCE_RETURN_POINT,"NAV_FENCE_RETURN_POINT"},
    {MAV_CMD_NAV_FENCE_POLYGON_VERTEX_INCLUSION,"NAV_FENCE_POLYGON_VERTEX_INCLUSION"},
    {MAV_CMD_NAV_FENCE_POLYGON_VERTEX_EXCLUSION,"NAV_FENCE_POLYGON_VERTEX_EXCLUSION"},
    {MAV_CMD_NAV_FENCE_CIRCLE_INCLUSION,"NAV_FENCE_CIRCLE_INCLUSION"},
    {MAV_CMD_NAV_FENCE_CIRCLE_EXCLUSION,"NAV_FENCE_CIRCLE_EXCLUSION"},
    {MAV_CMD_NAV_RALLY_POINT,"NAV_RALLY_POINT"},
    {MAV_CMD_UAVCAN_GET_NODE_INFO,"UAVCAN_GET_NODE_INFO"},
    {MAV_CMD_DO_ADSB_OUT_IDENT,"DO_ADSB_OUT_IDENT"},
    {MAV_CMD_PAYLOAD_PREPARE_DEPLOY,"PAYLOAD_PREPARE_DEPLOY"},
    {MAV_CMD_PAYLOAD_CONTROL_DEPLOY,"PAYLOAD_CONTROL_DEPLOY"},
    {MAV_CMD_FIXED_MAG_CAL_YAW ,"FIXED_MAG_CAL_YAW"},
    {MAV_CMD_DO_WINCH,"DO_WINCH"},
    {MAV_CMD_WAYPOINT_USER_1,"WAYPOINT_USER_1"},
    {MAV_CMD_WAYPOINT_USER_2,"WAYPOINT_USER_2"},
    {MAV_CMD_WAYPOINT_USER_3,"WAYPOINT_USER_3"},
    {MAV_CMD_WAYPOINT_USER_4,"WAYPOINT_USER_4"},
    {MAV_CMD_WAYPOINT_USER_5,"WAYPOINT_USER_5"},
    {MAV_CMD_SPATIAL_USER_1,"SPATIAL_USER_1"},
    {MAV_CMD_SPATIAL_USER_2,"SPATIAL_USER_2"},
    {MAV_CMD_SPATIAL_USER_3,"SPATIAL_USER_3"},
    {MAV_CMD_SPATIAL_USER_4,"SPATIAL_USER_4"},
    {MAV_CMD_SPATIAL_USER_5,"SPATIAL_USER_5"},
    {MAV_CMD_USER_1,"USER_1"},
    {MAV_CMD_USER_2,"USER_2"},
    {MAV_CMD_USER_3,"USER_3"},
    {MAV_CMD_USER_4,"USER_4"},
    {MAV_CMD_USER_5,"USER_5"},
    {MAV_CMD_CAN_FORWARD,"CAN_FORWARD"}
};
#endif // STRUCTS_H
